A_SITE/annuity_app/urls.py
from django.urls import include, path

from . import views
from drf_auto_endpoint.router import router

from .models import Junk, Junk_Detail, Choice

router.register(Junk)
router.register(Junk_Detail)
router.register(Choice)

urlpatterns = [
    path('', include(router.urls)),
]

app_name = "annuity_app"
urlpatterns += [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="question_detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path('login/', views.LoginView.as_view()),
    path('register/', views.RegisterView.as_view()),
    path('profile/', views.ProfileView.as_view()),
    path('logout/', views.LogoutView.as_view()),
    path("csrf/", views.GetCSRFToken.as_view()),
    path("validatorHelp/", views.validatorHelp),
    path("junk/", views.CreateJunkView.as_view()),
    path("updatejunk/<int:pk>", views.UpdateJunkView.as_view()),
    path("listjunk/", views.ListJunkView.as_view()),
    path("opt/", views.GetMeta.as_view()),
]

A_SITE/annuity_app/models.py
import datetime

from django.db import models
from django.utils import timezone
from .muiFields import MuiCharField, MuiIntegerField

"""commit 2 change"""


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return (
            self.pub_date >= timezone.now() - datetime.timedelta(days=1)
            and self.pub_date < timezone.now()
        )


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Junk(models.Model):
    user_name = MuiCharField(
        max_length=100, mui_order=1, help_text='some helpful text', mui_width=200)
    password = MuiCharField(
        max_length=200)
    color = MuiCharField(max_length=200)
    age = MuiIntegerField(mui_order=1,
                          default=0,  help_text='age of a person as of last birth day')
    name = MuiCharField(max_length=200)


class Junk_Detail(models.Model):
    junk = models.ForeignKey(Junk,
                             on_delete=models.CASCADE, related_name='posts')
    text = models.CharField(max_length=200, default="")


modelDict = {
    'Junk': Junk,
    'Junk_Detail': Junk_Detail,
}

A_SITE/annuity_app/templates/annuity_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>My home page</title>
  </head>
  <body>
    {% if question_list %}
    <ul>
      {% for question in question_list %}
      <li>
        <a href="{% url 'annuity_app:question_detail' question.id %}"
          >{{ question.question_text }}</a
        >
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
  </body>
</html>

A_SITE/annuity_app/templates/annuity_app/question_detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>My home page</title>
  </head>
  <body>
    <form action="{% url 'annuity_app:vote' question.id %}" method="post">
      {% csrf_token %}
      <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %} {% for choice in question.choice_set.all %}
        <input
          type="radio"
          name="choice"
          id="choice{{ forloop.counter }}"
          value="{{ choice.id }}"
        />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
        ><br />
        {% endfor %}
      </fieldset>
      <input type="submit" value="Vote" />
    </form>
  </body>
</html>

A_SITE/annuity_app/templates/annuity_app/results.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>
    {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize
    }}
  </li>
  {% endfor %}
</ul>

<a href="{% url 'annuity_app:question_detail' question.id %}">Vote again?</a>